server:
  port: 9100 # 伺服器的port號
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:coindesk;DB_CLOSE_DELAY=-1' # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password:  # database 密碼
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
